version: '3'
volumes:
  database:
services:
  db:
    container_name: dg-sql-server
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    ports: 
      - 1433:1433
    volumes:
      - database:/var/lib/sqlserver/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      SA_PASSWORD: "Datagrupo#123456"
      ACCEPT_EULA: "Y"
   